
services:
  backend:
    image: backend-backend
    build: .
    volumes:
      - ./volume:/app/data
    networks:
      - gezcez-net
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25565/health"]
      interval: 10s
      timeout: 3s
      retries: 3
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - gezcez-net
  #   depends_on:
  #     - gezcez_backend
  #   deploy:
  #     replicas: 1
      # restart_policy:
        # condition: on-failure
networks:
  gezcez-net:
    driver: overlay